### ISSUE TITLE
Provide a sync API

### ISSUE THREAD

**Issue by 3rd-Eden** [jcoglan/vault-cipher#1]
Are there any plans to add `sync` API instead of `async` only? I've looked at the code and as far as I know it's possible for `node` as all the API's that this module uses have sync counter parts.

**Comment by jcoglan** [comment]
I've recently moved this module to require at least Node 0.10, which means we can use `crypto.pbkdf2Sync()` and it makes the code cleaner since the `crypto` APIs are known to return buffers.

The next release will only offer a sync API, per the updated README.
